// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Visitor_Management_System2019student.Data;

namespace Visitor_Management_System2019student.Migrations
{
    [DbContext(typeof(visitorDBcontext))]
    partial class visitorDBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Visitor_Management_System2019student.Models.StaffNames", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Department");

                    b.Property<string>("Name");

                    b.Property<int>("VisitorCount");

                    b.HasKey("Id");

                    b.ToTable("StaffNames");
                });

            modelBuilder.Entity("Visitor_Management_System2019student.Models.Visitors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Business");

                    b.Property<DateTime>("DateIn");

                    b.Property<DateTime>("DateOut");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int?>("StaffNameId");

                    b.HasKey("Id");

                    b.HasIndex("StaffNameId");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("Visitor_Management_System2019student.Models.Visitors", b =>
                {
                    b.HasOne("Visitor_Management_System2019student.Models.StaffNames", "StaffName")
                        .WithMany()
                        .HasForeignKey("StaffNameId");
                });
#pragma warning restore 612, 618
        }
    }
}
